In [1]:
import pandas as pd

In [8]:
star_wars = pd.read_csv("StarWars.csv", encoding = "ISO-8859-1")
star_wars.head()

,RespondentID,Have you seen any of the 6 films in the Star Wars franchise?,Do you consider yourself to be a fan of the Star Wars film franchise?,Which of the following Star Wars films have you seen? Please select all that apply.,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.,...,Unnamed: 28,Which character shot first?,Are you familiar with the Expanded Universe?,Do you consider yourself to be a fan of the Expanded Universe?æ,Do you consider yourself to be a fan of the Star Trek franchise?,Gender,Age,Household Income,Education,Location (Census Region)
0,NaN,Response,Response,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,Star Wars: Episode I The Phantom Menace,...,Yoda,Response,Response,Response,Response,Response,Response,Response,Response,Response
1,3.292880e+09,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,3,...,Very favorably,I don't understand this question,Yes,No,No,Male,18-29,NaN,High school degree,South Atlantic
2,3.292880e+09,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Yes,Male,18-29,"$0 - $24,999",Bachelor degree,West South Central
3,3.292765e+09,Yes,No,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,NaN,NaN,NaN,1,...,Unfamiliar (N/A),I don't understand this question,No,NaN,No,Male,18-29,"$0 - $24,999",High school degree,West North Central
4,3.292763e+09,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,5,...,Very favorably,I don't understand this question,No,NaN,Yes,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central

In [9]:
star_wars.columns

Index(['RespondentID',
       'Have you seen any of the 6 films in the Star Wars franchise?',
       'Do you consider yourself to be a fan of the Star Wars film franchise?',
       'Which of the following Star Wars films have you seen? Please select all that apply.',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14',
       'Please state whether you view the following characters favorably, unfavorably, or are unfamiliar with him/her.',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27',
       'Unnamed: 28', 'Which character shot first?',
       'Are you familiar with the Expanded Universe?',
       'Do you consider yourself to be a fan of the Expanded Universe?æ',
       'Do you consider yourself to be a fan of the Star Trek franchise?',
       'Gender', 'Age', 'Household Income', 'Education',
       'Location (Census Region)'],
      dtype='object')

In [14]:
for column in star_wars.columns:
    null_values = star_wars[column].isnull().sum()
    print(f"Null values in {column}:")
    print(null_values)
    print("***")

Null values in RespondentID:
0
***
Null values in Have you seen any of the 6 films in the Star Wars franchise?:
0
***
Null values in Do you consider yourself to be a fan of the Star Wars film franchise?:
350
***
Null values in Which of the following Star Wars films have you seen? Please select all that apply.:
513
***
Null values in Unnamed: 4:
615
***
Null values in Unnamed: 5:
636
***
Null values in Unnamed: 6:
579
***
Null values in Unnamed: 7:
428
***
Null values in Unnamed: 8:
448
***
Null values in Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.:
351
***
Null values in Unnamed: 10:
350
***
Null values in Unnamed: 11:
351
***
Null values in Unnamed: 12:
350
***
Null values in Unnamed: 13:
350
***
Null values in Unnamed: 14:
350
***
Null values in Please state whether you view the following characters favorably, unfavorably, or are unfamiliar with him/her.:
357
***
Null values in Unnamed: 16:
355
***
Null values in Unnamed: 17:
355
***
Null values in Unnamed: 18:
363
***
Null values in Unnamed: 19:
361
***
Null values in Unnamed: 20:
372
***
Null values in Unnamed: 21:
360
***
Null values in Unnamed: 22:
366
***
Null values in Unnamed: 23:
374
***
Null values in Unnamed: 24:
359
***
Null values in Unnamed: 25:
356
***
Null values in Unnamed: 26:
365
***
Null values in Unnamed: 27:
372
***
Null values in Unnamed: 28:
360
***
Null values in Which character shot first?:
358
***
Null values in Are you familiar with the Expanded Universe?:
358
***
Null values in Do you consider yourself to be a fan of the Expanded Universe?æ:
973
***
Null values in Do you consider yourself to be a fan of the Star Trek franchise?:
118
***
Null values in Gender:
140
***
Null values in Age:
140
***
Null values in Household Income:
328
***
Null values in Education:
150
***
Null values in Location (Census Region):
143
***

In [10]:
star_wars = star_wars[pd.notnull(star_wars['RespondentID'])]

In [ ]:
yes_no ={
    "Yes": True,
    "No": False
}

star_wars["Have you seen any of the 6 films in the Star Wars franchise?"] = star_wars["Have you seen any of the 6 films in the Star Wars franchise?"].map(yes_no)
star_wars["Do you consider yourself to be a fan of the Star Wars film franchise?"] = star_wars["Do you consider yourself to be a fan of the Star Wars film franchise?"].map(yes_no)